import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import ThemeToggleButton from "./components/theme-toggle-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let colorTheme = (await cookies()).get("color-theme");

  console.log("This is the color theme I got back", colorTheme);

  let theme;
  if (colorTheme) {
    theme = colorTheme.value;
  } else {
    theme = "light";
  }

  return (
    <html lang="en" data-theme={theme}>
      <body>{children}</body>
    </html>
  );
}
